[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "vite"       # auto-detects Vite
  # remove the port line to avoid conflicts
[build.environment]
  NODE_VERSION = "18"